#!/bin/sh

{
  echo "APP_NAME='$APP_NAME'"
  echo "APP_ENV='$APP_ENV'"
  echo "APP_KEY='$APP_KEY'"
  echo "APP_URL='$APP_URL'"
  echo "APP_DEBUG='$APP_DEBUG'"
  echo "FILESYSTEM_DRIVER='$FILESYSTEM_DRIVER'"
  echo "FIREBASE_CREDENTIALS='$FIREBASE_CREDENTIALS'"
  echo " GOOGLE_APPLICATION_CREDENTIALS='$GOOGLE_APPLICATION_CREDENTIALS'"
} >> .env
